name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_maps_flutter: ^2.9.0
  file_picker: ^8.0.0
  video_player: ^2.8.2
  image_picker: ^1.2.1
 
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  audioplayers: ^6.5.1
  record: ^6.1.2
  permission_handler: ^12.0.1
  connectivity_plus: ^6.1.2
  url_launcher: ^6.3.1
  http_parser: ^4.0.0
  sqflite: ^2.2.8
  path: ^1.8.3
  socket_io_client: ^2.0.3
  fluttertoast: ^8.2.4
  provider: ^6.1.2
  
  mime: ^1.0.4

  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^20.0.0



 
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/logo.jpeg"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: images/logo.jpeg
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - images/logo.jpeg
